version: '3'

services:
  robot:
    build:
      dockerfile: Dockerfile
      context: ./RobotFramework
    ports:
      - "3008:3008"
    tty: true
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
  mongo:
    build:
      dockerfile: Dockerfile
      context: ./backend/database
    ports:
      - "27019:27017"
    tty: true
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend/api
    ports:
      - "1337:1337"
    tty: true
