version: '3'

services:
  robot:
    build:
      dockerfile: Dockerfile
      context: ./RobotFramework
    ports:
      - "3008:3008"
    tty: true
  mongo:
    image: mongo
    ports:
      - "2717:27017"

