version: '3'

services:
  robot:
    build:
      dockerfile: Dockerfile
      context: ./RobotFramework
    ports:
      - "3008:3008"
    tty: true
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "2717:27017"

